### PR TITLE
added golibs reference

### PR DESCRIPTION
**Pull request by PI-Victor**
didn't find any ref for go lib support for yaml so i thought i'd help out

### CODE REVIEW

**Comment by ixti** [comment]
:+1:

**Comment by trans** [comment]
Question, what is `index.txt` vs `index.html`? Doesn't one need to change the .txt file instead of the .html file b/c the html is generated from it via the Makefile?

**Comment by ixti** [comment]
@trans my bad. completely forgot about that. Honestly I'm gonna prepare a complete rewrite to utilize jekyll (and as result GitHub pages) instead :D

**Comment by PI-Victor** [comment]
thanks for the merge. i did check that in the beginning, but i don't see the links to be generated from there, that's why i went for the html directly, am i missing something?
at least there not in the index.txt, didn't check all the txt files though.

**Pull request merged**
